//
//  GameScoreImages.swift
//  PickleballReferee
//
//  Created by Tom Trompeter on 7/28/22.
//

import RealmSwift
import SwiftUI

class GameScoreImages: Object, ObjectKeyIdentifiable {
    
    @Persisted(primaryKey: true) var id: ObjectId
    
    // Images for game 1 Team 1 points boxes - default values
    @Persisted var point1Game1ImageTm1 = "squareleft"
    @Persisted var point2Game1ImageTm1 = "squareleft"
    @Persisted var point3Game1ImageTm1 = "squareleft"
    @Persisted var point4Game1ImageTm1 = "squareleft"
    @Persisted var point5Game1ImageTm1 = "squareleft"
    @Persisted var point6Game1ImageTm1 = "squareleft"
    @Persisted var point7Game1ImageTm1 = "squareleft"
    @Persisted var point8Game1ImageTm1 = "squareleft"
    @Persisted var point9Game1ImageTm1 = "squareleft"
    @Persisted var point10Game1ImageTm1 = "squareleft"
    @Persisted var point11Game1ImageTm1 = "squareleft"
    @Persisted var point12Game1ImageTm1 = "squareleft"
    @Persisted var point13Game1ImageTm1 = "squareleft"
    @Persisted var point14Game1ImageTm1 = "squareleft"
    @Persisted var point15Game1ImageTm1 = "squareleft"
    @Persisted var point16Game1ImageTm1 = "squareleft"
    @Persisted var point17Game1ImageTm1 = "squareleft"
    @Persisted var point18Game1ImageTm1 = "squareleft"
    @Persisted var point19Game1ImageTm1 = "squareleft"
    @Persisted var point20Game1ImageTm1 = "squareleft"
    @Persisted var point21Game1ImageTm1 = "square"
    
    // Images for game 2 Team 1 points boxes - default values
    @Persisted var point1Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point2Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point3Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point4Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point5Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point6Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point7Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point8Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point9Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point10Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point11Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point12Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point13Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point14Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point15Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point16Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point17Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point18Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point19Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point20Game2ImageTm1 = "squaremiddleleft"
    @Persisted var point21Game2ImageTm1 = "squaremiddleright"
    
    // Images for game 3 Team 1 points boxes - default values
    @Persisted var point1Game3ImageTm1 = "squareleft"
    @Persisted var point2Game3ImageTm1 = "squareleft"
    @Persisted var point3Game3ImageTm1 = "squareleft"
    @Persisted var point4Game3ImageTm1 = "squareleft"
    @Persisted var point5Game3ImageTm1 = "squareleft"
    @Persisted var point6Game3ImageTm1 = "squareleft"
    @Persisted var point7Game3ImageTm1 = "squareleft"
    @Persisted var point8Game3ImageTm1 = "squareleft"
    @Persisted var point9Game3ImageTm1 = "squareleft"
    @Persisted var point10Game3ImageTm1 = "squareleft"
    @Persisted var point11Game3ImageTm1 = "squareleft"
    @Persisted var point12Game3ImageTm1 = "squareleft"
    @Persisted var point13Game3ImageTm1 = "squareleft"
    @Persisted var point14Game3ImageTm1 = "squareleft"
    @Persisted var point15Game3ImageTm1 = "squareleft"
    @Persisted var point16Game3ImageTm1 = "squareleft"
    @Persisted var point17Game3ImageTm1 = "squareleft"
    @Persisted var point18Game3ImageTm1 = "squareleft"
    @Persisted var point19Game3ImageTm1 = "squareleft"
    @Persisted var point20Game3ImageTm1 = "squareleft"
    @Persisted var point21Game3ImageTm1 = "square"
    
    // Images for game 1 Team 2 points boxes - default values
    @Persisted var point1Game1ImageTm2 = "squareleft"
    @Persisted var point2Game1ImageTm2 = "squareleft"
    @Persisted var point3Game1ImageTm2 = "squareleft"
    @Persisted var point4Game1ImageTm2 = "squareleft"
    @Persisted var point5Game1ImageTm2 = "squareleft"
    @Persisted var point6Game1ImageTm2 = "squareleft"
    @Persisted var point7Game1ImageTm2 = "squareleft"
    @Persisted var point8Game1ImageTm2 = "squareleft"
    @Persisted var point9Game1ImageTm2 = "squareleft"
    @Persisted var point10Game1ImageTm2 = "squareleft"
    @Persisted var point11Game1ImageTm2 = "squareleft"
    @Persisted var point12Game1ImageTm2 = "squareleft"
    @Persisted var point13Game1ImageTm2 = "squareleft"
    @Persisted var point14Game1ImageTm2 = "squareleft"
    @Persisted var point15Game1ImageTm2 = "squareleft"
    @Persisted var point16Game1ImageTm2 = "squareleft"
    @Persisted var point17Game1ImageTm2 = "squareleft"
    @Persisted var point18Game1ImageTm2 = "squareleft"
    @Persisted var point19Game1ImageTm2 = "squareleft"
    @Persisted var point20Game1ImageTm2 = "squareleft"
    @Persisted var point21Game1ImageTm2 = "square"
    
    // Images for game 2 Team 2 points boxes - default values
    @Persisted var point1Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point2Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point3Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point4Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point5Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point6Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point7Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point8Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point9Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point10Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point11Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point12Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point13Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point14Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point15Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point16Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point17Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point18Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point19Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point20Game2ImageTm2 = "squaremiddleleft"
    @Persisted var point21Game2ImageTm2 = "squaremiddleright"
    
    // Images for game 3 Team 2 points boxes - default values
    @Persisted var point1Game3ImageTm2 = "squareleft"
    @Persisted var point2Game3ImageTm2 = "squareleft"
    @Persisted var point3Game3ImageTm2 = "squareleft"
    @Persisted var point4Game3ImageTm2 = "squareleft"
    @Persisted var point5Game3ImageTm2 = "squareleft"
    @Persisted var point6Game3ImageTm2 = "squareleft"
    @Persisted var point7Game3ImageTm2 = "squareleft"
    @Persisted var point8Game3ImageTm2 = "squareleft"
    @Persisted var point9Game3ImageTm2 = "squareleft"
    @Persisted var point10Game3ImageTm2 = "squareleft"
    @Persisted var point11Game3ImageTm2 = "squareleft"
    @Persisted var point12Game3ImageTm2 = "squareleft"
    @Persisted var point13Game3ImageTm2 = "squareleft"
    @Persisted var point14Game3ImageTm2 = "squareleft"
    @Persisted var point15Game3ImageTm2 = "squareleft"
    @Persisted var point16Game3ImageTm2 = "squareleft"
    @Persisted var point17Game3ImageTm2 = "squareleft"
    @Persisted var point18Game3ImageTm2 = "squareleft"
    @Persisted var point19Game3ImageTm2 = "squareleft"
    @Persisted var point20Game3ImageTm2 = "squareleft"
    @Persisted var point21Game3ImageTm2 = "square"
    
    // Images for timeout boxes - default values
    var timeOut1Game1ImageTm1 = "squareleft"
    var timeOut2Game1ImageTm1 = "squareleft"
    var timeOut3Game1ImageTm1 = "square"
    var timeOut1Game2ImageTm1 = "squaremiddleleft"
    var timeOut2Game2ImageTm1 = "squaremiddleleft"
    var timeOut3Game2ImageTm1 = "squaremiddleright"
    var timeOut1Game3ImageTm1 = "squareleft"
    var timeOut2Game3ImageTm1 = "squareleft"
    var timeOut3Game3ImageTm1 = "square"
    
    var timeOut1Game1ImageTm2 = "squareleft"
    var timeOut2Game1ImageTm2 = "squareleft"
    var timeOut3Game1ImageTm2 = "square"
    var timeOut1Game2ImageTm2 = "squaremiddleleft"
    var timeOut2Game2ImageTm2 = "squaremiddleleft"
    var timeOut3Game2ImageTm2 = "squaremiddleright"
    var timeOut1Game3ImageTm2 = "squareleft"
    var timeOut2Game3ImageTm2 = "squareleft"
    var timeOut3Game3ImageTm2 = "square"
    
    override class func primaryKey() -> String? {
        return "id"
    }
}
